stages:
  - build
  - push

variables:
  IMAGE_NAME: "ghcr.io/${CI_PROJECT_NAMESPACE}/led-matrix-application-websocket"
  DOCKER_HOST: tcp://docker:2375/  # Für Docker-in-Docker

# Docker-in-Docker Service für Builds
services:
  - docker:dind

before_script:
  - echo "Setting up environment"
  - docker --version

build_docker_image:
  stage: build
  script:
    - echo "Building Docker image..."
    - docker buildx create --use
    - docker buildx build --platform linux/arm/v6 \
        -t ${IMAGE_NAME}:${CI_COMMIT_REF_NAME} \
        -t ${IMAGE_NAME}:latest \
        --push .
  only:
    - tags
    - main
  tags:
    - docker

push_to_ghcr:
  stage: push
  script:
    - echo "Logging in to GitHub Container Registry..."
    - echo "${GHCR_TOKEN}" | docker login ghcr.io -u "${GITLAB_USER_NAME}" --password-stdin
    - echo "Pushing image..."
    - docker push ${IMAGE_NAME}:${CI_COMMIT_REF_NAME}
    - docker push ${IMAGE_NAME}:latest
  only:
    - tags
  tags:
    - docker
