name: Build Pillow and Docker Image

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  PY_VER: "3.9"
  PILLOW_VERSION: "10.3.0"
  CACHE_KEY: "pillow-10.3.0-py3.9-armv6-v10.3.0-v4"

jobs:
  # Job 1: Pillow-Wheel ARMv6 bauen
  build-pillow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Restore wheels cache
        id: cache-restore
        uses: actions/cache@v4
        with:
          path: wheels
          key: ${{ env.CACHE_KEY }}

      - name: Build Pillow wheel if not cached
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: |
          echo "Cache miss. Building new Pillow wheel for ARMv6..."

          docker buildx build \
            --platform linux/arm/v6 \
            -f Dockerfile.pillow-wheel \
            --build-arg PILLOW_VERSION="${PILLOW_VERSION}" \
            --tag pillow-builder:latest \
            --load .

          mkdir -p wheels

          CONTAINER_ID=$(docker create --platform linux/arm/v6 pillow-builder:latest)

          docker cp "${CONTAINER_ID}:/out/." ./wheels/

          docker rm "${CONTAINER_ID}"
      - name: Save wheels cache
        if: steps.cache-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: wheels
          key: ${{ env.CACHE_KEY }}

      - name: Verify that wheel artifact exists
        run: |
          ls -lR wheels
          if [ ! -f wheels/pillow-*.whl ]; then 
            echo "::error::Pillow wheel file not found in wheels/ directory!"
            exit 1
          fi

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: pillow-wheels
          path: wheels/

  # Job 2: Multi-arch Docker bauen & pushen, nutzt das Wheel-Artifact
  build-and-push:
    runs-on: ubuntu-latest
    needs: build-pillow

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download wheel artifact
        uses: actions/download-artifact@v4
        with:
          name: pillow-wheels
          path: wheels/

      - name: Verify wheels in build context
        run: ls -lR wheels

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PY_VER }}

      - name: Install Poetry
        run: pip install poetry poetry-plugin-export

      - name: Export requirements.txt
        run: |
          cd src
          poetry export -f requirements.txt --output requirements.txt --without-hashes

      - name: Set repository owner to lowercase
        id: string-actions
        run: echo "OWNER_LC=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 2. Verwende die im vorherigen Schritt erstellte Variable
      - name: Build and Push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm/v6
          push: true
          tags: |
            ghcr.io/${{ steps.string-actions.outputs.OWNER_LC }}/led-matrix-application-websocket:latest
            ghcr.io/${{ steps.string-actions.outputs.OWNER_LC }}/led-matrix-application-websocket:${{ github.ref_name }}