name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Oder die Version, die du benötigst

      - name: Install Poetry
        run: |
          pip install poetry-plugin-export

      - name: Export requirements.txt
        run: |
           cd src/
           poetry export -f requirements.txt --output requirements.txt --without-hashes

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          VERSION="${{ github.ref_name }}"
          IMAGE_NAME="led-matrix-application-websocket"
          REPOSITORY_OWNER_LOWERCASE=$(echo "${{ github.actor }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_TAG_LATEST="latest"
          IMAGE_TAG_VERSION="${VERSION}"
          
          echo "🚀 Building the image with tags: ${IMAGE_TAG_LATEST} and ${IMAGE_TAG_VERSION}"
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm/v6,linux/arm/v7 \
            -t ghcr.io/${REPOSITORY_OWNER_LOWERCASE}/${IMAGE_NAME}:${IMAGE_TAG_LATEST} \
            -t ghcr.io/${REPOSITORY_OWNER_LOWERCASE}/${IMAGE_NAME}:${IMAGE_TAG_VERSION} \
            --push .

      - name: Clean up
        run: |
          echo "🧹 Cleaning up requirements.txt..."
          rm -f src/requirements.txt
