name: Build and Release Docker Image

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm/v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image for ARMv6
        run: |
          docker buildx build \
            --platform linux/arm/v6 \
            --output type=docker,dest=led-matrix-application-websocket-${{ github.ref_name }}.tar \
            -t led-matrix-application-websocket:${{ github.ref_name }} .

      - name: Create GitHub Release and Upload Image
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: led-matrix-application-websocket-${{ github.ref_name }}.tar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
