name: Build and Push Docker Image to GHCR

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker buildx build \
            --platform linux/arm/v6 \
            --push \
            -t ghcr.io/${{ github.repository_owner }}/led-matrix-application-websocket:latest \
            -t ghcr.io/${{ github.repository_owner }}/led-matrix-application-websocket:${{ github.ref_name }} \
            .

      - name: Output success
        run: echo "Docker image successfully pushed to GHCR!"
